[build]
  command = "npm run build"
  publish = "visions"
  functions = "netlify/functions"

[[redirects]]
  from = "/static/*"
  to = "/.netlify/functions/server/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

# For SPA routing - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200