[build]
  command = "npm run build"
  publish = "visions"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = "visions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# For SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200